### ISSUE TITLE
Add a membership whitelist

### ISSUE THREAD

**Issue by MattyIce** [MattyIce/communitybot#2]
Add a setting pointing to a whitelist file that contains a list of steem account names who are allowed to sign up for a bot membership. Anyone not on the whitelist will not be allowed a membership.

**Comment by KINGdotNET** [comment]
Hi Matt,
Looking forward to see this feature added to the community bot.
Thank you.

**Comment by rafestrape** [comment]
Hi, thanks for the published work, I'm trying to launch a communitybot
I see it very useful because if the bot lease SP delegation, the landlord is targeted as a member of the community and will be voted. 
Anyway, I do not see where to enter the white list, by default anyone who makes a sufficient income is listed.
For now I can only manually delete this member, from members.json, stop and reboot communitybot.js with pm2

regards 
@rafestrape

**Comment by KINGdotNET** [comment]
@rafestrape Matt still working on this feature.

**Comment by MattyIce** [comment]
Sorry for the long wait guys, I've been swamped with work the past few weeks. I've just added the whitelist option in this commit: https://github.com/MattyIce/communitybot/commit/ab06a599af1961e3290094dfb23af681d912be25

I've done some testing locally but please let me know if you see any issues.
